# Diccionario de traducción de palabras latinas a españolas
diccionario = {
    "amicus": "amigo",
    "terra": "tierra",
    "lux": "luz",
    "aqua": "agua",
    "ventus": "viento",
    "rosa": "rosa",
    "sol": "sol",
    "deus": "dios",
    "ecclesia": "iglesia",
    "spiritus": "espíritu",
    "angelus": "ángel",
    "sanctus": "santo",
    "fides": "fe",
    "veritas": "verdad",
    "salvator": "salvador",
    "cristus": "cristo",
    "ordo": "orden",
    "virtus": "virtud",
    "gratia": "gracia",
    "lux": "luz",
    "rex": "rey",
    "regina": "reina",
    "mors": "muerte",
    "vita": "vida",
    "sacerdos": "sacerdote",
    "oratio": "oración",
    "credo": "credo",
    "gloria": "gloria",
    "alleluia": "aleluya",
    "pax": "paz",
    "caritas": "caridad",
    "misericordia": "misericordia",
    "dominus": "señor",
    "lux": "luz",
    "sacramentum": "sacramento",
    "benedictus": "bendito",
    "mater": "madre",
    "pater": "padre",
    "lux": "luz",
    "frater": "hermano",
    "soror": "hermana",
    "via": "camino",
    "terra": "tierra",
    "luna": "luna",
    "natura": "naturaleza",
    "vita": "vida",
    "familia": "familia",
    "domus": "casa",
    "ventus": "viento",
    "ignis": "fuego",
    "mare": "mar",
    "noctis": "noche",
    "dies": "día",
    "mundus": "mundo",
    "civitas": "ciudad",
    "insula": "isla",
    "flumen": "río",
    "mons": "montaña",
    "arbor": "árbol",
    "hortus": "jardín",
    "agricola": "agricultor",
    "mercator": "comerciante",
    "magister": "maestro",
    "doctus": "culto",
    "servus": "esclavo",
    "liber": "libre",
    "vitae": "vida",
    "morbus": "enfermedad",
    "mendicus": "pobre",
    "dives": "rico",
    "pauper": "pobre",
    "mensa": "mesa",
    "lectus": "cama",
    "scutum": "escudo",
    "gladius": "espada",
    "arcus": "arco",
    "sagitta": "flecha",
    "cibus": "comida",
    "potio": "bebida",
    "puer": "niño",
    "puella": "niña",
    "senex": "anciano",
    "senior": "anciano",
    "iuvenis": "joven",
    "juvenis": "joven",
    "filius": "hijo",
    "filia": "hija",
    "frater": "hermano",
    "soror": "hermana",
    "uxor": "esposa",
    "vir": "hombre",
    "mulier": "mujer",
    "genus": "género",
    "species": "especie",
    "animus": "alma",
    "cor": "corazón",
    "spiritus": "espíritu",
    "anima": "ánima",
    "mentis": "mente",
    "intellectus": "intelecto",
    "memoria": "memoria",
    "voluntas": "voluntad",
    "scientia": "ciencia",
    "doctrina": "doctrina",
    "ratio": "razón",
    "virtus": "virtud",
    "potentia": "poder",
    "potestas": "potestad",
    "libertas": "libertad",
    "justitia": "justicia",
    "pax": "paz",
    "fortuna": "fortuna",
    "fama": "fama",
    "gloria": "gloria",
    "honor": "honor",
    "laus": "alabanza",
    "victoria": "victoria",
    "bellum": "guerra",
    "hostis": "enemigo",
    "amicitia": "amistad",
    "caritas": "caridad",
    "fidelitas": "fidelidad",
    "veritas": "verdad",
    "clementia": "clemencia",
    "misericordia": "misericordia",
    "pudicitia": "pudor",
    "pudor": "pudor",
    "sapientia": "sabiduría",
    "sapiens": "sabio",
    "idoneus": "idóneo",
    "auctoritas": "autoridad",
    "dignitas": "dignidad",
    "humilitas": "humildad",
    "modestia": "modestia",
    "aestimatio": "estima",
    "fiducia": "confianza",
    "timor": "temor",
    "spes": "esperanza",
    "desiderium": "deseo",
    "gaudium": "gozo",
    "tristitia": "tristeza",
    "luxuria": "lujuria",
    "ira": "ira",
    "invidia": "envidia",
    "avaritia": "avaricia",
    "superbia": "soberbia",
    "desidia": "pereza",
    "gula": "gula",
    "lux": "luz",
    "caligo": "oscuridad",
    "tenebrae": "tinieblas",
    "umbra": "sombra",
    "nox": "noche",
    "diurnus": "diurno",
    "meridies": "mediodía",
    "vesper": "tarde",
    "mane": "mañana",
    "nocturnus": "nocturno",
    "aurora": "aurora",
    "crepusculum": "crepúsculo",
    "occasus": "ocaso",
    "orior": "salir",
    "occido": "caer",
    "hodie": "hoy",
    "heri": "ayer",
    "cras": "mañana",
    "nunc": "ahora",
    "tunc": "entonces",
    "semper": "siempre",
    "numquam": "nunca",
    "iam": "ya",
    "tamen": "sin embargo",
    "vero": "en verdad",
    "itaque": "por lo tanto",
    "igitur": "por lo tanto",
    "enim": "pues",
    "autem": "pero",
    "sed": "pero",
    "quidem": "ciertamente",
    "vero": "en verdad",
    "neque": "ni",
    "nec": "ni",
    "etiam": "también",
    "item": "también",
    "magis": "más",
    "minus": "menos",
    "sicut": "como",
    "similis": "similar",
    "tam": "tan",
    "tantus": "tan grande",
    "tantum": "sólo",
    "adeo": "tan",
    "quasi": "casi",
    "ita": "así",
    "sic": "así",
    "inde": "de ahí",
    "eodem": "al mismo lugar",
    "alius": "otro",
    "alter": "otro",
    "uter": "cuál de los dos",
    "quis": "quién",
    "quid": "qué",
    "qualis": "qué tipo de",
    "quantus": "cuánto",
    "quando": "cuándo",
    "ubi": "dónde",
    "unde": "de dónde",
    "quomodo": "cómo",
    "cur": "por qué",
    "quia": "porque",
    "quoniam": "ya que",
    "ut": "como",
    "cum": "con",
    "sine": "sin",
    "pro": "a favor de",
    "contra": "en contra de",
    "ante": "antes",
    "post": "después",
    "apud": "entre",
    "inter": "entre",
    "intra": "dentro",
    "extra": "fuera",
    "circa": "alrededor de",
    "per": "a través de",
    "secundum": "según",
    "propter": "a causa de",
    "ob": "a causa de",
    "ad": "hacia",
    "versus": "hacia",
    "contra": "en contra de",
    "prope": "cerca de",
    "cum": "cuando",
    "dum": "mientras",
    "quando": "cuando",
    "quandoquidem": "puesto que",
    "quia": "porque",
    "cumque": "cuando sea que",
    "ne": "no",
    "non": "no",
    "num": "acaso",
    "an": "o",
    "utrum": "si",
    "vel": "o",
    "aut": "o",
    "aut...aut": "o...o",
    "sive": "ya sea que",
    "seu": "ya sea que",
    "tamquam": "como si",
    "quasi": "casi",
    "velut": "como",
    "ut": "para que",
    "ne": "para que no",
    "utinam": "ojalá",
    "nonne": "acaso no",
    "num": "acaso",
    "numquid": "acaso",
    "nescio": "no sé",
    "nolo": "no quiero",
    "nolle": "no querer",
    "novi": "conozco",
    "novisse": "conocer",
    "opto": "desear",
    "persto": "permanecer firme",
    "possum": "poder",
    "posse": "poder",
    "probo": "aprobar",
    "prohibeo": "prohibir",
    "puto": "pensar",
    "quasi": "casi",
    "queo": "ser capaz de",
    "quidem": "ciertamente",
    "rogo": "pedir",
    "scio": "saber",
    "scire": "saber",
    "spero": "esperar",
    "sto": "estar de pie",
    "sum": "ser",
    "sumo": "tomar",
    "supero": "superar",
    "taceo": "callar",
    "teneo": "tener",
    "timeo": "temer",
    "tollo": "levantar",
    "traho": "atraer",
    "vaco": "estar vacío",
    "valeo": "ser fuerte",
    "venio": "venir",
    "vereor": "temer",
    "verto": "girar",
    "video": "ver",
    "vivo": "vivir",
    "voco": "llamar",
    "volo": "querer",
    "volvo": "rodar",
    # Agrega más palabras según sea necesario
}


# Función principal para traducir palabras latinas a españolas y validar gramática
def traducir_palabra(palabra_latina):
    if palabra_latina in diccionario:
        palabra_espanol = diccionario[palabra_latina]
        return f"La traducción de '{palabra_latina}' es '{palabra_espanol}'."
    else:
        return f"No se encontró una traducción para '{palabra_latina}'."

# Loop para interactuar con el usuario
while True:
    palabra_latina = input("Ingresa una palabra latina (o 'salir' para terminar): ").strip().lower()

    if palabra_latina == "salir":
        print("¡Adiós!")
        break

    resultado = traducir_palabra(palabra_latina)
    print(resultado)
